[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'npm install --prefix server',
  'npm install --prefix client'
]

[phases.build]
cmds = [
  'npm run build --prefix client'
]

[start]
cmd = 'cd server && npm start'