[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'npm install --prefix server --production=false',
  'npm install --prefix client --production=false'
]

[phases.build]
cmds = [
  'npm run build --prefix client'
]

[start]
cmd = 'cd server && NODE_ENV=production npm start'