services:
  - type: web
    name: couples-budget-tracker
    env: node
    plan: free
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: cd server && NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: render-super-secret-jwt-key-2024-couples-budget-tracker-production